name: Argo .NET Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Archive Base Content Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Base Content Debug
          path: |
           Argo Base Content/bin/Debug/**
          retention-days: 30
      - name: Archive Core Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Core Debug
          path: |
            Argo Core/bin/Debug/**
          retention-days: 30
      - name: Archive Editor Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Editor Debug
          path: |
            Argo Editor/bin/Debug/**
          retention-days: 30
      - name: Archive Tools Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tools Debug
          path: |
            Argo Tools/bin/Debug/**
          retention-days: 30
      - name: Archive Utilities Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Utilities Debug
          path: |
            Argo Utilities/bin/Debug/**
          retention-days: 30
      - name: Archive Playground Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Playground Debug
          path: |
            Playground/bin/Debug/**
          retention-days: 30
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: .NET Tests        # Name of the check run which will be created
          path: ./**/*.trx            # Path to test results
          reporter: dotnet-trx        # Format of test results
          
