name: Argo .NET Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Archive Debug Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Debug
          path: |
            bin/Debug/net6.0/**
          retention-days: 30
      - name: Archive Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: |
            bin/Release/net6.0/**
          retention-days: 30
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: .NET Tests Dev        # Name of the check run which will be created
          path: ./**/*.trx            # Path to test results
          reporter: dotnet-trx        # Format of test results
          